image: maven:3.3-jdk-8

build:
  script: mvn install -U -Dmaven.javadoc.skip=true
  artifacts:
    paths:
      - server/target/lance-server-jar-with-dependencies.jar
      - install/docker_retry.sh

